### PR TITLE
Update site to accomidate new cookie banner changes

### PR DESCRIPTION
**Pull request by brown-a2**
Changes include,

- Add standardization to theme by adding new hook to header. This also provides a hook for cookie plugin.
- Update composer to point to correct cookie banner. *This will need to be changed again when we carry out the accessibility changes however, this site needed to be urgently updated as it was pointing to a branch of the plugin that no longer exists.

### CODE REVIEW

**Review by BNewing — APPROVED** [review]
Looks good to me :)

**Comment by RobLoweMOJ** [comment]
Hey looks good. Just a quick question. Could you not just do do_action('wp_body_open'); Or does the wp_body_open  function get overridden by the cookie plugin?

**Comment by brown-a2** [comment]
@RobLoweMOJ good question, as far as I understand it "wp_body_open()" function is exactly the same as using the do_action ... except wrapping everything up like that helps for theme backward compatibility ... themes being used before wp_body_open() was a thing....err I doubt our theme will ever be used in that way but I just put it in as a "good practice" but we don't need it.

**Comment by RobLoweMOJ** [comment]
To clarify you can override and extend do_action so just wanted to now why it needs to be wrapped in a function. Not a big thing.. just curious.

**Comment by brown-a2** [comment]
Also just one more thing @RobLoweMOJ ...remember we started using do_action('after_body_open_tag');  as a custom theme hook to hook into... it turns out the more standardized hook that I'm using above, already exists in most themes and is what is normally used, so I've gone with it and I'm removing our custom hook :(

**Comment by RobLoweMOJ** [comment]
kool. no probs. Feel free to merge. The only thing i would say thats my personal preference is to keep functions out of template files. But we can discuss this when we get to the nightingale theme.

**Review by RobLoweMOJ — APPROVED** [review]
👍

**Comment by brown-a2** [comment]
Oh I think I see what you mean... basically what is happening is that it's checking and if it finds that wp_body_open() isn't there...it creates it using that function that is wrapped in the if conditional... and then that function can be used as if it was there all along. Yeah, definitely agree about the function thing... I've only got it here as this is an ALB refresh site.

**Pull request merged**
